services:
  - type: web
    name: inventory-backend
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /actuator/health   # scoate dacă nu ai actuator
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=75.0"
